package org.lendingclub.trident.agent;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import org.lendingclub.trident.agent.Main;

import static org.junit.Assert.*;

import org.assertj.core.api.Assertions;

public class DockerEventAgentTest {
    @Test public void test() {
     
    	DockerEventAgent agent = new DockerEventAgent();
    	
    	Assertions.assertThat(agent.getTridentBaseUrl()).isEqualTo("http://localhost:8080");
    }
}
