package org.lendingclub.trident.cli;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import org.lendingclub.trident.cli.Main;

import static org.junit.Assert.*;

public class AppTest {
	@Test
	public void testNothing() {

	}
}
