#!/bin/bash


TRIDENT_URL=${TRIDENT_URL-"http://localhost:8080"}
SWARM_NAME=$1
SWARM_TEMPLATE=$2

if [ "SWARM_TEMPLATE" = "" ]; then
	echo "usage: $0 <name> <template>"
	exit 99
fi

if [ "$SWARM_NAME" = "" ]; then
	echo "usage: $0 <name> <template>"
	exit 99
fi

cat <<EOF

TRIDENT_URL.   : $TRIDENT_URL
SWARM_NAME     : $SWARM_NAME
SWARM_TEMPLATE : $SWARM_TEMPLATE

EOF

cat <<EOF | curl -k -X POST -d @- -H "Content-type: application/json" ${TRIDENT_URL}/api/trident/aws/swarm/create

{
	"name":"${SWARM_NAME}",
 	"template":"${SWARM_TEMPLATE}"
}
EOF


